title: reroot-log
description: 개발자를 위한 Docs 입니다.
baseurl: "/"
url: https://reroot-log.github.io/
theme: just-the-docs
repository: reroot-log/reroot-log.github.io


aux_links:
  "reroot-log-github":
  - "https://github.com/reroot-log/reroot-log.github.io"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/reroot-log/reroot-log.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: nil
